sudo: required
dist: trusty
language: rust
branches:
  only:
  - master
matrix:
  fast_finish: false
  include:
  - rust: stable
cache:
  apt: true
  directories:
  - "$TRAVIS_BUILD_DIR/target"
  - "$HOME/.cargo"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - gcc-4.8
    - g++-4.8
    - oracle-java8-set-default
script:
- echo 'Running tests' && echo -en 'travis_fold:start:tests'
- cargo test --all
- echo -en 'travis_fold:end:tests'
- echo 'Building in release mode' && echo -en 'travis_fold:start:build.release'
- cargo build --release
- echo -en 'travis_fold:end:build.release'
- echo 'Running bench from ./tools/bench.sh' && echo -en 'travis_fold:start:bench'
- "./tools/bench.sh"
- echo -en 'travis_fold:end:bench'
after_success: |
  [ true ] &&
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = stable ] &&
  ./tools/doc.sh &&
  echo '<meta http-equiv=refresh content=0;url=pzec/index.html>' > target/doc/index.html &&
  pip install --user ghp-import &&
  /home/travis/.local/bin/ghp-import -n target/doc &&
  git push -fq https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
  - CXX="g++-4.8"
  - CC="gcc-4.8"
  - RUST_BACKTRACE=1
  - secure: vSSTEZvJ/HPs46scn29WjM6eih5IYpsADNZoFSQoQaqGBMux82gBPipvO/znfbm/0HJInqLX+iJGRsbH8X3LP/cqTD009hE7fGZnTH53vTviwrYJVD0Ty4cl9p8/OQqdOVsAMWQ1GjXUrBKjhFIzid9EFsXdQrXHdjt4+ajE1+yQiXnHtnBys675+fzAHnNNFxaxtPwPn+HFD4KC1iWn0PCfqyBA8CZdwFJUT/ECp9SgHimIuXDYKT0EPWFiZhEd7RQKF3aoGgWnPhqwaFvc3tvvoDdsAe5o2NyolxQCcyK4SUc0O9pmBmUK4nbLuEub44jOrYsqx4N+Oo413dgRbbTH0deGQuNfjWfWVB1CEy3v2ATtBC1B0dpaFLybYJLZhOAaoPXHONdsEPoDkW0ZX0dEn4CREgt1GjNPyZKdfURjti2Qaj8QWQ9ftQ22BBWeE+F8//5uFwUXViEJsUDoJd+USXDOTD05Wy2SdG7NZeSkbIDCuoX6ycO+s33sdBH39j3+Oeh39wnwfQ0P/Evc6lKQqld2DTIuP1mh/OmD/Qqby4h3uUtcTynKKfEYXUY1CX0/IE5HE5gbZdYyFSzPEAVww/HFI13bjQ1/Ax92FJQMNkGfP4DkzutFcx3ML8aW0gyrwNIV59Fgft16kmuyJTEmkKRyg7A/iO9m9I3Q9fU=
